permalink: /:year:month:day/:title
url: https://june-storm.github.io/ #Your url here
baseurl: /

# variables
name: document of Mellepage
description: writen by June
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true